### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np

vector = np.linspace(10, 49, 40)
print(vector)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np

arr = np.arange(9)
matrix = arr.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np

arr = np.random.rand(10, 10)
min_val = np.min(arr)
max_val = np.max(arr)

print("Array:")
print(arr)
print("\nMinimum value: ", min_val)
print("Maximum value: ", max_val)

Array:
[[0.57659324 0.84250248 0.83124023 0.19818974 0.37686345 0.10310596
  0.21366995 0.34749538 0.17158043 0.96509046]
 [0.09617587 0.24189681 0.78295068 0.21045482 0.45678562 0.73343147
  0.72080928 0.5588876  0.96701566 0.5584737 ]
 [0.986222   0.07446528 0.96456923 0.40433001 0.72530677 0.00143174
  0.98703591 0.92141122 0.70793916 0.03333667]
 [0.63828376 0.48614105 0.9188682  0.55549268 0.17719963 0.38737034
  0.41359647 0.64802787 0.88579672 0.3367599 ]
 [0.52427508 0.66294617 0.07424295 0.52031389 0.01638997 0.48857264
  0.89946003 0.05912217 0.49417826 0.38846782]
 [0.26364269 0.64744128 0.93881704 0.82784362 0.10718213 0.62026663
  0.14159497 0.02084312 0.73332505 0.66063033]
 [0.47835145 0.59480746 0.64579321 0.47587232 0.16595296 0.65560091
  0.30231899 0.16748392 0.39483565 0.38170644]
 [0.87999216 0.31022635 0.65325732 0.82776384 0.44745734 0.42548906
  0.75744979 0.30862783 0.41340728 0.29598829]
 [0.14731134 0.11153422 0.15357084 0.00569732 0.49623645 0.30835534
  0.2

### 6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np

vec = np.random.rand(30)
mean_val = np.mean(vec)

print("Vector:")
print(vec)
print("\nMean value: ", mean_val)

Vector:
[0.39938137 0.00331363 0.38603153 0.69635739 0.84267884 0.46724564
 0.98314373 0.85492494 0.75537434 0.87418652 0.51034219 0.09539005
 0.95661494 0.33293993 0.90502757 0.0514077  0.58356567 0.48160569
 0.32764577 0.75229876 0.84948139 0.33423127 0.23657562 0.5952562
 0.40620028 0.2680548  0.41345462 0.11998843 0.43358936 0.35190569]

Mean value:  0.5089404627680201
